### ISSUE TITLE
🐛 [BUG] - 2 files with same name

### ISSUE THREAD

**Issue by ThomasSed** [anomic30/Storz#104]
### Description

when uploading files, if you are uploading a file (same one or an other one) with the same name, it'll be stored. 
The user must be advertised and specify his intention

### Reproduction URL

https://github.com/ThomasSed/Storz

### Reproduction steps

```bash
1. Go to "home"
2. Click on "upload"
3. upload a file
4. do the 3 first steps a second time, with the same file (for example) 
5. go to your repository, you must see 2 files with same name
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

**Comment by anomic30** [comment]
Hi, @ThomasSed,
If a user uploads the same file even with different file names, it will generate the same CID. So we can check if that CID already exists in the user's document and we can show him some message like: 

"This file already exists with the name ABC. Do you want to upload the same file again?"

Now, we have to find a way to generate the CID without uploading it to IPFS first.

**Comment by mani-rsg** [comment]
Would like to work on this. Can you assign this to me? @anomic30

**Comment by anomic30** [comment]
Hi @mani-rsg,
We are not assigning issues to anyone. Only the first PR related to the issue will be considered.

**Comment by mani-rsg** [comment]
Oh ok sure Then will this count on Hactoberfest ?

**Comment by anomic30** [comment]
@mani-rsg yes

**Comment by mani-rsg** [comment]
Hi @anomic30,  instead of looking for how to generate the CID that is generated after the upload. My suggestion is 

1. To filter for same name, if we found one, we can say like _"A file with the same name already exists, do you want to override it?"_ If yes we will upload & override, else we don't upload.

2. To perform the delete operation using the `unique _id` which is by default generated by MongoDB. By doing this, the exact item at which the delete is performed will be deleted.

Let me know if this works. I have done the local setup, based on your confirmation I will start working on this. Thanks

**Comment by mani-rsg** [comment]
@anomic30 Can you please confirm, if I can go with this approach?

**Comment by anomic30** [comment]
@mani-rsg, yes you can start working.
