### ISSUE TITLE
💡 [REQUEST] - Add middleware to do data sanitization against NOSQL query injection and XSS and Implement a global error handling controller

### ISSUE THREAD

**Issue by BiswajitSahoo-tech** [anomic30/Storz#53]
### Start Date

09/04/2022

### Summary

- Want to add some middleware that will prevent cross-site scripting and NoSQL query injection.

- Also want to implement a global error handler, which means after catching errors all over the application we send the error to a global error handler which will decide what to do with it.

### Basic Example

Let on user.js we get an error which will go to catch section

e,g 
   ```
 try{
      //......
     }catch( err) {
         next( err) // calling the global err handler
     }
```

And in index.js we have the global error handler which will be called

index.js

```
app.use( (err, req, res, next) => {
          res.status( err.statuscode) . json( {
          data: err.message
          })
});
```

### Drawbacks

There is no drawback of adding above features

**Comment by ezehlivinus** [comment]
@BiswajitSahoo-tech the error controller should be middleware I suggest.

cc/
@anomic30

**Comment by BiswajitSahoo-tech** [comment]
@ezehlivinus 
Sure, it is actually a middleware, But since we are following the MVC model and errorcontroller decides how error data get displayed, therefore I preferred to keep this file under controller/ dir

**Comment by ezehlivinus** [comment]
The code was written in a controller/ folder...it should be in the middleware.

Controllers are meant to handle HTTP requests...

The error handler should be a middleware not a controller.

Also, in API or microservice, the V in MVC is omitted because there is no View especially as there is a dedicated frontend project for the API.

Error handler, and...then the controllers does not determine how errors and responses are displayed the frontend app determines that. What your API need to do is to return the necessary info needed by the frontend.  

Restful API does not really follow MVC. However, it has model, controller, services (service was what @Onesco was naming data-repo....).

When building API (a standalone app with coupling frontend into it) MVC are usually not a thing and omitted as a result, but some convention are retained.

API does not have a view (V) because it only return JSON or another form of data exchange, not view(HTML page + static files)
